parameters:
  jobTemplate: ''
  variables: []
  osGroup: ''
  osSubgroup: ''
  archType: ''
  container: ''
  pool: ''
  platform: ''
  shouldContinueOnError: false
  jobParameters: {}

jobs:
- template: ${{ parameters.jobTemplate }}
  parameters:
    variables: ${{ parameters.variables }}
    osGroup: ${{ parameters.osGroup }}
    osSubgroup: ${{ parameters.osSubgroup }}
    archType: ${{ parameters.archType }}
    container: ${{ parameters.container }}
    pool: ${{ parameters.pool }}
    platform: ${{ parameters.platform }}
    shouldContinueOnError: ${{ parameters.shouldContinueOnError }}
    helixQueues:

    # OSX arm64
    - ${{ if eq(parameters.platform, 'osx_arm64') }}:
      - osx.13.arm64.open
      - osx.14.arm64.open
      - osx.15.arm64.open
      - osx.26.arm64.open

    # OSX x64
    - ${{ if eq(parameters.platform, 'osx_x64') }}:
      - osx.13.amd64.open
      - osx.14.amd64.open
      - osx.15.amd64.open
      - osx.26.amd64.open

    ${{ insert }}: ${{ parameters.jobParameters }}
